[versions]
agp = "8.8.0"
coreKtx = "1.15.0"
kotlin = "2.0.20"
kotlinxSerializationJson = "1.5.1"
okhttp = "4.12.0"
prelude-core-sdk = "0.2.0"

[libraries]
android-build-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
prelude-core-sdk = { module = "so.prelude.android:core-sdk", version.ref = "prelude-core-sdk" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
